name: Publish
description: Publish artifacts online

inputs:
  isRelease:
    type: boolean
    default: false
  publish:
    type: boolean
    default: true

runs:
  using: "composite"
  steps:

  - name: Install Apptainer
    uses: eWaterCycle/setup-apptainer@v2
    with:
      apptainer-version: 1.2.5

  - name: Download Prerequisites
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/update-release
      chmod u+x ./update-release

  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
      pattern: packages-*
      merge-multiple: true
      path: ${{ github.workspace }}/packages

  - name: Publish on GitHub (Release)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'true' }}
    shell: bash
    run: |
      echo "Release tag will be: ${{ env.npVersion }}"
      echo "Release name will be: ${{ env.npVersion }}"
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/np -t ${{ env.npVersion }} -n "${{ env.npVersion }}" -f ReleaseNotes.md packages/*

  - name: Publish on GitHub (Continuous)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'false' }}
    shell: bash
    run: |
      echo "Release tag will be: continuous"
      echo "Release name will be: 'Continuous (${{ env.npVersion }} @ ${{ env.npShortHash }})'"
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/np -t continuous -p -e -u -n "Continuous (${{ env.npVersion }} @ ${{ env.npShortHash }})" -b "Continuous release from \`develop\` branch @ ${{ env.npShortHash }}. Built $(date)." packages/*

  - name: Publish on Harbor (Release)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'true' }}
    shell: bash
    run: |
      echo "Release tag will be: latest"
      apptainer remote login --username ${HARBOR_USER} --password ${HARBOR_SECRET} docker://harbor.stfc.ac.uk
      ${SINGULARITY_ROOT}/bin/apptainer push packages/np-${{ env.npVersion }}.sif oras://harbor.stfc.ac.uk/isis_disordered_materials/np:latest

  - name: Publish on Harbor (Continuous)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'false' }}
    shell: bash
    run: |
      echo "Release tag will be: continuous"
      apptainer remote login --username ${HARBOR_USER} --password ${HARBOR_SECRET} docker://harbor.stfc.ac.uk
      ${SINGULARITY_ROOT}/bin/apptainer push packages/np-${{ env.npVersion }}.sif oras://harbor.stfc.ac.uk/isis_disordered_materials/np:continuous
